/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppSuperRouteImport } from './routes/app.super'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ApiAiMindmapRouteImport } from './routes/api.ai-mindmap'
import { Route as ApiAiInsightsRouteImport } from './routes/api.ai-insights'
import { Route as AppMindmapIndexRouteImport } from './routes/app.mindmap.index'
import { Route as AppMindmapBoardIdRouteImport } from './routes/app.mindmap.$boardId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperRoute = AppSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiAiMindmapRoute = ApiAiMindmapRouteImport.update({
  id: '/api/ai-mindmap',
  path: '/api/ai-mindmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiInsightsRoute = ApiAiInsightsRouteImport.update({
  id: '/api/ai-insights',
  path: '/api/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMindmapIndexRoute = AppMindmapIndexRouteImport.update({
  id: '/mindmap/',
  path: '/mindmap/',
  getParentRoute: () => AppRoute,
} as any)
const AppMindmapBoardIdRoute = AppMindmapBoardIdRouteImport.update({
  id: '/mindmap/$boardId',
  path: '/mindmap/$boardId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/ai-insights': typeof ApiAiInsightsRoute
  '/api/ai-mindmap': typeof ApiAiMindmapRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/super': typeof AppSuperRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/': typeof AppIndexRoute
  '/app/mindmap/$boardId': typeof AppMindmapBoardIdRoute
  '/app/mindmap/': typeof AppMindmapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/ai-insights': typeof ApiAiInsightsRoute
  '/api/ai-mindmap': typeof ApiAiMindmapRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/super': typeof AppSuperRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app': typeof AppIndexRoute
  '/app/mindmap/$boardId': typeof AppMindmapBoardIdRoute
  '/app/mindmap': typeof AppMindmapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/ai-insights': typeof ApiAiInsightsRoute
  '/api/ai-mindmap': typeof ApiAiMindmapRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/super': typeof AppSuperRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/': typeof AppIndexRoute
  '/app/mindmap/$boardId': typeof AppMindmapBoardIdRoute
  '/app/mindmap/': typeof AppMindmapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/ai-insights'
    | '/api/ai-mindmap'
    | '/app/admin'
    | '/app/analytics'
    | '/app/settings'
    | '/app/super'
    | '/app/timeline'
    | '/app/'
    | '/app/mindmap/$boardId'
    | '/app/mindmap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/ai-insights'
    | '/api/ai-mindmap'
    | '/app/admin'
    | '/app/analytics'
    | '/app/settings'
    | '/app/super'
    | '/app/timeline'
    | '/app'
    | '/app/mindmap/$boardId'
    | '/app/mindmap'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/ai-insights'
    | '/api/ai-mindmap'
    | '/app/admin'
    | '/app/analytics'
    | '/app/settings'
    | '/app/super'
    | '/app/timeline'
    | '/app/'
    | '/app/mindmap/$boardId'
    | '/app/mindmap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAiInsightsRoute: typeof ApiAiInsightsRoute
  ApiAiMindmapRoute: typeof ApiAiMindmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/super': {
      id: '/app/super'
      path: '/super'
      fullPath: '/app/super'
      preLoaderRoute: typeof AppSuperRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ai-mindmap': {
      id: '/api/ai-mindmap'
      path: '/api/ai-mindmap'
      fullPath: '/api/ai-mindmap'
      preLoaderRoute: typeof ApiAiMindmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-insights': {
      id: '/api/ai-insights'
      path: '/api/ai-insights'
      fullPath: '/api/ai-insights'
      preLoaderRoute: typeof ApiAiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/mindmap/': {
      id: '/app/mindmap/'
      path: '/mindmap'
      fullPath: '/app/mindmap/'
      preLoaderRoute: typeof AppMindmapIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mindmap/$boardId': {
      id: '/app/mindmap/$boardId'
      path: '/mindmap/$boardId'
      fullPath: '/app/mindmap/$boardId'
      preLoaderRoute: typeof AppMindmapBoardIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuperRoute: typeof AppSuperRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMindmapBoardIdRoute: typeof AppMindmapBoardIdRoute
  AppMindmapIndexRoute: typeof AppMindmapIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuperRoute: AppSuperRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppIndexRoute: AppIndexRoute,
  AppMindmapBoardIdRoute: AppMindmapBoardIdRoute,
  AppMindmapIndexRoute: AppMindmapIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAiInsightsRoute: ApiAiInsightsRoute,
  ApiAiMindmapRoute: ApiAiMindmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
